using Microsoft.EntityFrameworkCore;

namespace EventRegistrationSystem.Data;

public static class IdentitySchemaBootstrapper
{
    public static async Task EnsureIdentitySchemaAsync(EventDbContext context, CancellationToken cancellationToken = default)
    {
        var commands = new[]
        {
            """
            ALTER TABLE event_users ADD COLUMN IF NOT EXISTS "UserName" character varying(255);
            ALTER TABLE event_users ADD COLUMN IF NOT EXISTS "NormalizedUserName" character varying(255);
            ALTER TABLE event_users ADD COLUMN IF NOT EXISTS "NormalizedEmail" character varying(255);
            ALTER TABLE event_users ADD COLUMN IF NOT EXISTS "EmailConfirmed" boolean NOT NULL DEFAULT FALSE;
            ALTER TABLE event_users ADD COLUMN IF NOT EXISTS "SecurityStamp" text;
            ALTER TABLE event_users ADD COLUMN IF NOT EXISTS "ConcurrencyStamp" text;
            ALTER TABLE event_users ADD COLUMN IF NOT EXISTS "PhoneNumber" text;
            ALTER TABLE event_users ADD COLUMN IF NOT EXISTS "PhoneNumberConfirmed" boolean NOT NULL DEFAULT FALSE;
            ALTER TABLE event_users ADD COLUMN IF NOT EXISTS "TwoFactorEnabled" boolean NOT NULL DEFAULT FALSE;
            ALTER TABLE event_users ADD COLUMN IF NOT EXISTS "LockoutEnd" timestamp with time zone;
            ALTER TABLE event_users ADD COLUMN IF NOT EXISTS "LockoutEnabled" boolean NOT NULL DEFAULT TRUE;
            ALTER TABLE event_users ADD COLUMN IF NOT EXISTS "AccessFailedCount" integer NOT NULL DEFAULT 0;
            """,
            """
            UPDATE event_users
            SET "UserName" = COALESCE(NULLIF("UserName", ''), "Email"),
                "NormalizedUserName" = COALESCE(NULLIF("NormalizedUserName", ''), UPPER(COALESCE(NULLIF("UserName", ''), "Email"))),
                "NormalizedEmail" = COALESCE(NULLIF("NormalizedEmail", ''), UPPER("Email")),
                "EmailConfirmed" = TRUE,
                "SecurityStamp" = COALESCE(NULLIF("SecurityStamp", ''), md5(random()::text || clock_timestamp()::text)),
                "ConcurrencyStamp" = COALESCE(NULLIF("ConcurrencyStamp", ''), md5(random()::text || clock_timestamp()::text)),
                "LockoutEnabled" = TRUE
            WHERE "Email" IS NOT NULL;
            """,
            """
            CREATE TABLE IF NOT EXISTS identity_roles
            (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Name" character varying(256),
                "NormalizedName" character varying(256),
                "ConcurrencyStamp" text
            );
            """,
            """
            CREATE TABLE IF NOT EXISTS identity_role_claims
            (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "RoleId" integer NOT NULL REFERENCES identity_roles("Id") ON DELETE CASCADE,
                "ClaimType" text,
                "ClaimValue" text
            );
            """,
            """
            CREATE TABLE IF NOT EXISTS identity_user_claims
            (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "UserId" integer NOT NULL REFERENCES event_users("Id") ON DELETE CASCADE,
                "ClaimType" text,
                "ClaimValue" text
            );
            """,
            """
            CREATE TABLE IF NOT EXISTS identity_user_logins
            (
                "LoginProvider" character varying(128) NOT NULL,
                "ProviderKey" character varying(128) NOT NULL,
                "ProviderDisplayName" text,
                "UserId" integer NOT NULL REFERENCES event_users("Id") ON DELETE CASCADE,
                CONSTRAINT "PK_identity_user_logins" PRIMARY KEY ("LoginProvider", "ProviderKey")
            );
            """,
            """
            CREATE TABLE IF NOT EXISTS identity_user_roles
            (
                "UserId" integer NOT NULL REFERENCES event_users("Id") ON DELETE CASCADE,
                "RoleId" integer NOT NULL REFERENCES identity_roles("Id") ON DELETE CASCADE,
                CONSTRAINT "PK_identity_user_roles" PRIMARY KEY ("UserId", "RoleId")
            );
            """,
            """
            CREATE TABLE IF NOT EXISTS identity_user_tokens
            (
                "UserId" integer NOT NULL REFERENCES event_users("Id") ON DELETE CASCADE,
                "LoginProvider" character varying(128) NOT NULL,
                "Name" character varying(128) NOT NULL,
                "Value" text,
                CONSTRAINT "PK_identity_user_tokens" PRIMARY KEY ("UserId", "LoginProvider", "Name")
            );
            """,
            """
            CREATE UNIQUE INDEX IF NOT EXISTS "UserNameIndex"
                ON event_users ("NormalizedUserName")
                WHERE "NormalizedUserName" IS NOT NULL;
            """,
            """
            CREATE INDEX IF NOT EXISTS "EmailIndex"
                ON event_users ("NormalizedEmail");
            """,
            """
            CREATE UNIQUE INDEX IF NOT EXISTS "RoleNameIndex"
                ON identity_roles ("NormalizedName")
                WHERE "NormalizedName" IS NOT NULL;
            """,
            """
            CREATE INDEX IF NOT EXISTS "IX_identity_role_claims_RoleId"
                ON identity_role_claims ("RoleId");
            """,
            """
            CREATE INDEX IF NOT EXISTS "IX_identity_user_claims_UserId"
                ON identity_user_claims ("UserId");
            """,
            """
            CREATE INDEX IF NOT EXISTS "IX_identity_user_logins_UserId"
                ON identity_user_logins ("UserId");
            """,
            """
            CREATE INDEX IF NOT EXISTS "IX_identity_user_roles_RoleId"
                ON identity_user_roles ("RoleId");
            """
        };

        foreach (var command in commands)
        {
            await context.Database.ExecuteSqlRawAsync(command, cancellationToken);
        }
    }
}
